# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8bef8ba0d602ca6329d587b1d9e811a1343ce80d59037d8ae0855344625b375b33d400b4cacef1ead938f2c84982788a52bcf7b351ddc618745fefecafe6a4

test:
  secret_key_base: 480a154e2bd295d6d47b274218d0354ec0af5735deb124d75576b6f841994f6d22695bdeeaf59f91a9994bce32e8b1ac3371353dbc5b877f9c5cd9be8cdb5088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
